#!/usr/bin/env -S deno run --allow-all

/**
 * MSI Installer Generator for Windows
 * Uses WiX Toolset to create MSI packages
 */

import $ from "jsr:@david/dax@0.42.0";
import { parseArgs } from "jsr:@std/cli@1.0.6/parse-args";
import { walk } from "jsr:@std/fs@1.0.5/walk";
import { relative, join, basename, extname } from "jsr:@std/path@1.0.6";
import { config } from "./build.config.ts";

// コマンドライン引数のパース
const args = parseArgs(Deno.args, {
  string: ["config", "output"],
  default: {
    config: "Release",
    output: "dist",
  },
});

interface InstallerConfig {
  productName: string;
  version: string;
  manufacturer: string;
  upgradeCode: string;
  installDir: string;
  sourceDir: string;
  outputDir: string;
  outputName: string;
}

interface FileEntry {
  id: string;
  name: string;
  source: string;
}

// UUIDを生成
function generateUUID(): string {
  return crypto.randomUUID().toUpperCase();
}

// ファイルIDを生成（WiXでは英数字とアンダースコアのみ許可）
function generateFileId(filename: string): string {
  const sanitized = filename.replace(/[^a-zA-Z0-9_]/g, "_");
  return `File_${sanitized}_${generateUUID().slice(0, 8)}`;
}

// コンポーネントIDを生成
function generateComponentId(filename: string): string {
  const sanitized = filename.replace(/[^a-zA-Z0-9_]/g, "_");
  return `Component_${sanitized}_${generateUUID().slice(0, 8)}`;
}

// ビルドフォルダ内のファイルを収集
async function collectFiles(sourceDir: string, excludeExtensions: string[]): Promise<FileEntry[]> {
  const files: FileEntry[] = [];

  try {
    for await (const entry of walk(sourceDir, { includeDirs: false })) {
      const filename = basename(entry.path);

      // ビルド中間ファイルを除外
      const ext = extname(filename).toLowerCase();
      if (excludeExtensions.includes(ext)) {
        continue;
      }

      files.push({
        id: generateFileId(filename),
        name: filename,
        source: entry.path,
      });
    }
  } catch (error) {
    console.error(`Error collecting files from ${sourceDir}:`, error);
  }

  return files;
}

// WiX XMLを生成
function generateWixXml(config: InstallerConfig, files: FileEntry[]): string {
  const componentEntries = files
    .map((file) => {
      const componentId = generateComponentId(file.name);
      return `
        <Component Id="${componentId}" Guid="${generateUUID()}">
          <File Id="${file.id}" Name="${file.name}" Source="${file.source}" KeyPath="yes" />
        </Component>`;
    })
    .join("\n");

  const componentRefs = files
    .map((file) => {
      const componentId = generateComponentId(file.name);
      // ComponentIdを再生成するのではなく、上で生成したものと一致させる必要があるため
      // 実際にはfilesにcomponentIdを保持する必要がある
      return `        <ComponentRef Id="${componentId}" />`;
    })
    .join("\n");

  // より正確な実装: ファイルとコンポーネントを一緒に管理
  const componentsWithRefs = files.map((file) => {
    const componentId = generateComponentId(file.name);
    return {
      componentXml: `
        <Component Id="${componentId}" Guid="${generateUUID()}">
          <File Id="${file.id}" Name="${file.name}" Source="${file.source}" KeyPath="yes" />
        </Component>`,
      refXml: `        <ComponentRef Id="${componentId}" />`,
      componentId,
    };
  });

  const componentXmls = componentsWithRefs.map((c) => c.componentXml).join("\n");
  const refXmls = componentsWithRefs.map((c) => c.refXml).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="*"
           Name="${config.productName}"
           Language="1033"
           Version="${config.version}"
           Manufacturer="${config.manufacturer}"
           UpgradeCode="${config.upgradeCode}">

    <Package InstallerVersion="500"
             Compressed="yes"
             InstallScope="perMachine"
             Description="${config.productName} Installer"
             Comments="This installer was generated by Deno MSI Generator" />

    <MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />

    <MediaTemplate EmbedCab="yes" />

    <Feature Id="ProductFeature" Title="${config.productName}" Level="1">
${refXmls}
    </Feature>

    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFiles64Folder">
        <Directory Id="INSTALLFOLDER" Name="${config.installDir}">
${componentXmls}
        </Directory>
      </Directory>
    </Directory>

    <!-- UI設定 -->
    <UIRef Id="WixUI_InstallDir" />
    <Property Id="WIXUI_INSTALLDIR" Value="INSTALLFOLDER" />

    <!-- ライセンス画面をスキップ（必要に応じてライセンスファイルを指定） -->
    <WixVariable Id="WixUILicenseRtf" Value="license.rtf" />

  </Product>
</Wix>`;
}

// シンプルなWiX XMLを生成（UI拡張なし）
function generateSimpleWixXml(config: InstallerConfig, files: FileEntry[]): string {
  const componentsWithRefs = files.map((file) => {
    const componentId = `Component_${file.id}`;
    return {
      componentXml: `
          <Component Id="${componentId}" Guid="${generateUUID()}">
            <File Id="${file.id}" Name="${file.name}" Source="${file.source}" KeyPath="yes" />
          </Component>`,
      refXml: `      <ComponentRef Id="${componentId}" />`,
    };
  });

  const componentXmls = componentsWithRefs.map((c) => c.componentXml).join("");
  const refXmls = componentsWithRefs.map((c) => c.refXml).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="*"
           Name="${config.productName}"
           Language="1033"
           Version="${config.version}"
           Manufacturer="${config.manufacturer}"
           UpgradeCode="${config.upgradeCode}">

    <Package InstallerVersion="500"
             Compressed="yes"
             InstallScope="perMachine"
             Description="${config.productName} Installer"
             Comments="This installer was generated by Deno MSI Generator" />

    <MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />

    <MediaTemplate EmbedCab="yes" />

    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFiles64Folder">
        <Directory Id="INSTALLFOLDER" Name="${config.installDir}">${componentXmls}
        </Directory>
      </Directory>
    </Directory>

    <Feature Id="ProductFeature" Title="${config.productName}" Level="1">
${refXmls}
    </Feature>

  </Product>
</Wix>`;
}

// WiX 4用のXMLを生成
function generateWix4Xml(cfg: InstallerConfig, files: FileEntry[]): string {
  const componentsWithRefs = files.map((file) => {
    const componentId = `Component_${file.id}`;
    return {
      componentXml: `
          <Component Id="${componentId}" Guid="${generateUUID()}">
            <File Id="${file.id}" Name="${file.name}" Source="${file.source}" />
          </Component>`,
      refXml: `      <ComponentRef Id="${componentId}" />`,
    };
  });

  const componentXmls = componentsWithRefs.map((c) => c.componentXml).join("");
  const refXmls = componentsWithRefs.map((c) => c.refXml).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Package Name="${cfg.productName}"
           Language="1033"
           Version="${cfg.version}"
           Manufacturer="${cfg.manufacturer}"
           UpgradeCode="${cfg.upgradeCode}"
           InstallerVersion="500"
           Compressed="yes"
           Scope="perMachine">

    <MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />

    <MediaTemplate EmbedCab="yes" />

    <StandardDirectory Id="ProgramFiles64Folder">
      <Directory Id="INSTALLFOLDER" Name="${cfg.installDir}">${componentXmls}
      </Directory>
    </StandardDirectory>

    <Feature Id="ProductFeature" Title="${cfg.productName}" Level="1">
${refXmls}
    </Feature>

  </Package>
</Wix>`;
}

interface WixCheckResult {
  available: boolean;
  path?: string;
  version: 3 | 4;
}

// WiXツールの存在確認
async function checkWixToolset(): Promise<WixCheckResult> {
  // WiX 4+ (wix.exe) - dotnet tool を先にチェック
  try {
    await $`wix --version`.quiet();
    return { available: true, path: "wix", version: 4 };
  } catch {
    // continue
  }

  // WiX 3.x (candle.exe, light.exe)
  const wix3Paths = [
    "C:\\Program Files (x86)\\WiX Toolset v3.11\\bin",
    "C:\\Program Files (x86)\\WiX Toolset v3.14\\bin",
    "C:\\Program Files\\WiX Toolset v3.11\\bin",
  ];

  for (const wixPath of wix3Paths) {
    try {
      const candlePath = join(wixPath, "candle.exe");
      await Deno.stat(candlePath);
      return { available: true, path: wixPath, version: 3 };
    } catch {
      // continue
    }
  }

  // PATH内のcandle.exeを確認
  try {
    await $`where candle.exe`.quiet();
    return { available: true, path: "", version: 3 };
  } catch {
    // continue
  }

  return { available: false, version: 3 };
}

// MSIをビルド
async function buildMsi(
  installerConfig: InstallerConfig,
  wixCheck: WixCheckResult
): Promise<void> {
  const wxsPath = join(installerConfig.outputDir, `${installerConfig.outputName}.wxs`);
  const wixobjPath = join(installerConfig.outputDir, `${installerConfig.outputName}.wixobj`);
  const msiPath = join(installerConfig.outputDir, `${installerConfig.outputName}.msi`);

  // ファイル収集
  console.log(`📁 Collecting files from: ${installerConfig.sourceDir}`);
  const files = await collectFiles(installerConfig.sourceDir, config.installer.excludeExtensions);

  if (files.length === 0) {
    throw new Error(`No files found in ${installerConfig.sourceDir}`);
  }

  console.log(`   Found ${files.length} files to package:`);
  for (const file of files) {
    console.log(`   - ${file.name}`);
  }

  // WXSファイル生成（WiXバージョンに応じて適切なXMLを生成）
  console.log(`\n📝 Generating WiX ${wixCheck.version} source file: ${wxsPath}`);
  const wxsContent = wixCheck.version === 4
    ? generateWix4Xml(installerConfig, files)
    : generateSimpleWixXml(installerConfig, files);
  await Deno.writeTextFile(wxsPath, wxsContent);

  // WiXでコンパイル
  console.log(`\n🔨 Compiling WiX source...`);

  if (wixCheck.version === 4) {
    // WiX 4+ (dotnet tool)
    await $`wix build ${wxsPath} -o ${msiPath} -arch x64`;
  } else {
    // WiX 3.x
    const wixPath = wixCheck.path || "";
    const candleExe = wixPath ? join(wixPath, "candle.exe") : "candle.exe";
    const lightExe = wixPath ? join(wixPath, "light.exe") : "light.exe";

    await $`${candleExe} -arch x64 -out ${wixobjPath} ${wxsPath}`;
    console.log(`\n📦 Linking MSI package...`);
    await $`${lightExe} -out ${msiPath} ${wixobjPath}`;
  }

  console.log(`\n✅ MSI installer created: ${msiPath}`);
}

// メイン処理
async function main(): Promise<void> {
  if (Deno.build.os !== "windows") {
    console.error("❌ MSI installer can only be created on Windows");
    Deno.exit(1);
  }

  console.log("🔧 MSI Installer Generator");
  console.log(`   Product: ${config.projectName} v${config.version}`);
  console.log(`   Configuration: ${args.config}`);
  console.log("");

  // WiXツールセットの確認
  console.log("🔍 Checking for WiX Toolset...");
  const wixCheck = await checkWixToolset();

  if (!wixCheck.available) {
    console.error("❌ WiX Toolset not found!");
    console.error("");
    console.error("Please install WiX Toolset:");
    console.error("  Option 1: Download WiX 3.x from https://wixtoolset.org/releases/");
    console.error("  Option 2: Install via winget: winget install WiXToolset.WiXToolset");
    console.error("  Option 3: Install via dotnet: dotnet tool install --global wix");
    Deno.exit(1);
  }

  console.log(`   WiX Toolset v${wixCheck.version} found${wixCheck.path && wixCheck.path !== "wix" ? ` at: ${wixCheck.path}` : ""}`);

  // 出力ディレクトリの作成
  await $`mkdir -p ${args.output}`;

  // ソースディレクトリの確認
  const sourceDir = join("build", args.config);
  try {
    const stat = await Deno.stat(sourceDir);
    if (!stat.isDirectory) {
      throw new Error("Not a directory");
    }
  } catch {
    console.error(`❌ Source directory not found: ${sourceDir}`);
    console.error("   Please run 'deno task build:release' first.");
    Deno.exit(1);
  }

  // インストーラー設定
  const installerConfig: InstallerConfig = {
    productName: config.projectName,
    version: config.version,
    manufacturer: config.author,
    upgradeCode: config.installer.upgradeCode,
    installDir: config.installer.installDir,
    sourceDir: sourceDir,
    outputDir: args.output,
    outputName: `${config.projectName}-${config.version}-x64`,
  };

  try {
    await buildMsi(installerConfig, wixCheck);
  } catch (error) {
    console.error("❌ MSI build failed:", error.message);
    Deno.exit(1);
  }
}

await main();
